import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import shadesOf, { hexToRgb } from "./shades.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../..");

const siteConfigPath = join(repoRoot, "src/data/site-config.json");

if(!existsSync(siteConfigPath)) {
	console.error(`Site config file not found at ${siteConfigPath}`);
	process.exit(1);
}

const siteConfig = JSON.parse(readFileSync(siteConfigPath, "utf8"));

const colors = siteConfig?.ui?.colors ?? {};
const fonts = siteConfig?.ui?.fonts ?? {};
const fontSize = fonts.font_size ?? { basePx: 16, scale: 0.25 };
const fontFamily = fonts.family ?? {};

const PRIMARY = colors.primary || "#434E5E";
const SECONDARY = colors.secondary || "#479FC8";
const ACCENT = colors.accent || "#05505C";

const palettes = {
	primary: shadesOf(PRIMARY),
	secondary: shadesOf(SECONDARY),
	accent: shadesOf(ACCENT),
};

const fontBase = Number(fontSize.basePx);
const fontScale = Number(fontSize.scale);
const headingSize = (mult) => Number(1 + fontScale * mult).toPrecision(2);

const themeLines = [];
const rootLines = [];

for (const [name, palette] of Object.entries(palettes)) {
	for (const [shade, hex] of Object.entries(palette)) {
		const value = stripVarFallback(hex);
		const key = shade === "DEFAULT" ? `--color-${name}` : `--color-${name}-${shade}`;
		themeLines.push(`\t${key}: ${value};`);
		const rgb = hexToRgb(value).toArray().join(", ");
		const rgbKey = shade === "DEFAULT" ? `--color-${name}-rgb` : `--color-${name}-${shade}-rgb`;
		rootLines.push(`\t${rgbKey}: ${rgb};`);
	}
}

themeLines.push("");
themeLines.push(`\t--font-size-base: ${fontBase}px;`);
themeLines.push(`\t--text-h1: ${headingSize(8)}rem;`);
themeLines.push(`\t--text-h2: ${headingSize(5)}rem;`);
themeLines.push(`\t--text-h3: ${headingSize(4)}rem;`);
themeLines.push(`\t--text-h4: ${headingSize(3)}rem;`);
themeLines.push(`\t--text-h5: ${headingSize(2)}rem;`);
themeLines.push(`\t--text-h6: 1rem;`);
themeLines.push("");

const primaryFamily = fontFamily.primary ? `var(--font-primary), ${fontFamily.primary_type || "sans-serif"}` : "var(--font-primary)";
const secondaryFamily = fontFamily.secondary ? `var(--font-secondary, var(--font-primary)), ${fontFamily.secondary_type || "sans-serif"}` : "var(--font-secondary, var(--font-primary))";
themeLines.push(`\t--font-primary: ${primaryFamily};`);
themeLines.push(`\t--font-secondary: ${secondaryFamily};`);
themeLines.push("");

themeLines.push(`\t--breakpoint-sm: 540px;`);
themeLines.push(`\t--breakpoint-md: 768px;`);
themeLines.push(`\t--breakpoint-lg: 1024px;`);
themeLines.push(`\t--breakpoint-xl: 1280px;`);
themeLines.push(`\t--breakpoint-2xl: 1536px;`);

rootLines.push("");
rootLines.push(`\t--color-gray-500-rgb: 107, 114, 128;`);
rootLines.push(`\t--color-white-rgb: 255, 255, 255;`);

const out = `/* AUTO-GENERATED by integrations/tailwind/generateThemeCss.mjs - do not edit by hand. */

@theme {
${themeLines.join("\n")}
}

:root {
${rootLines.join("\n")}
}
`;

writeFileSync(resolve(repoRoot, "src/assets/css/_theme.generated.css"), out, "utf8");
console.log("[generateThemeCss] wrote src/assets/css/_theme.generated.css");

function stripVarFallback(value) {
	if (typeof value !== "string") return value;
	const m = /var\([^,]+,\s*([^)]+)\)/.exec(value);
	return m ? m[1].trim() : value;
}
